"""empty message

Revision ID: 14d4ac0f0f1
Revises: None
Create Date: 2015-09-10 14:57:28.690904

"""

# revision identifiers, used by Alembic.
revision = '14d4ac0f0f1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc_addr', sa.String(length=35), nullable=True),
    sa.Column('payout_addr', sa.String(length=35), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('btc_addr')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer')
    ### end Alembic commands ###
