"""empty message

Revision ID: 1c91ee99cac
Revises: 14d4ac0f0f1
Create Date: 2015-11-04 07:23:19.991912

"""

# revision identifiers, used by Alembic.
revision = '1c91ee99cac'
down_revision = '14d4ac0f0f1'

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc_addr', sa.String(length=35), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_block'), 'audit', ['block'], unique=False)
    op.add_column('farmer', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.add_column('farmer', sa.Column('uptime', sa.Interval(), nullable=True))
    op.create_index(op.f('ix_farmer_last_seen'), 'farmer', ['last_seen'], unique=False)    
    farmer = sa.table('farmer',sa.column('reg_time'),sa.column('last_seen'))
    op.execute(farmer.update().values(reg_time=datetime.utcnow()))
    op.execute(farmer.update().values(last_seen=datetime.utcnow()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_last_seen'), table_name='farmer')
    op.drop_column('farmer', 'uptime')
    op.drop_column('farmer', 'reg_time')
    op.drop_index(op.f('ix_audit_block'), table_name='audit')
    op.drop_table('audit')
    ### end Alembic commands ###
