"""empty message

Revision ID: 1c9790acd60
Revises: 14d4ac0f0f1
Create Date: 2015-11-02 02:58:57.959981

"""

# revision identifiers, used by Alembic.
revision = '1c9790acd60'
down_revision = '14d4ac0f0f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('btc_addr', sa.String(length=35), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('response', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_block'), 'audit', ['block'], unique=False)
    op.add_column('farmer', sa.Column('reg_time', sa.DateTime(), nullable=True))
    op.add_column('farmer', sa.Column('uptime', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_farmer_last_seen'), 'farmer', ['last_seen'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_last_seen'), table_name='farmer')
    op.drop_column('farmer', 'uptime')
    op.drop_column('farmer', 'reg_time')
    op.drop_index(op.f('ix_audit_block'), table_name='audit')
    op.drop_table('audit')
    ### end Alembic commands ###
