"""empty message

Revision ID: 5fee40ea374b
Revises: 1c91ee99cac
Create Date: 2016-03-09 19:31:02.469386

"""

# revision identifiers, used by Alembic.
revision = '5fee40ea374b'
down_revision = '1c91ee99cac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farmer', sa.Column('bandwidth', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farmer', 'bandwidth')
    ### end Alembic commands ###
